version: '3'
services:
  postgres:
    image: x-postgres:latest  # 使用刚才构建的镜像
    container_name: x-postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    ports:
      - "${DATABSE_PORT}:5432"
    networks:
      - x-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  redis:
    image: x-redis:latest  # 使用刚才构建的镜像
    container_name: x-redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - brainx-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  x-network:
    driver: bridge
